DROP DATABASE IF EXISTS ASS5;
CREATE DATABASE ASS5;
USE ASS5;

CREATE TABLE RESULT(
	ROLL INT,
    SCODE INT,
    MARKS FLOAT,
    
    PRIMARY KEY (ROLL, SCODE)
);

CREATE TABLE BACKPAPER(
	ROLL INT,
    SCODE INT,
    PRIMARY KEY (ROLL, SCODE)
);

DELIMITER $$
CREATE TRIGGER BACKPAPER_CHECK_AFTER_INSERT AFTER INSERT ON RESULT
FOR EACH ROW
BEGIN
	IF NEW.MARKS < 50 THEN
		INSERT INTO BACKPAPER  (ROLL, SCODE) VALUES (NEW.ROLL, NEW.SCODE);
	ELSE 
		DELETE FROM BACKPAPER WHERE (ROLL, SCODE) = (NEW.ROLL, NEW.SCODE);
	END IF;	
END;$$

CREATE TRIGGER BACKPAPER_CHECK_AFTER_UPDATE AFTER UPDATE ON RESULT
FOR EACH ROW
BEGIN
	IF NEW.MARKS < 50 THEN
		INSERT INTO BACKPAPER  (ROLL, SCODE) VALUES (NEW.ROLL, NEW.SCODE);
	ELSE 
		DELETE FROM BACKPAPER WHERE (ROLL, SCODE) = (NEW.ROLL, NEW.SCODE);
	END IF;	
END;$$
DELIMITER ;

INSERT INTO RESULT (ROLL, SCODE, MARKS) VALUES (12, 5, 40);
INSERT INTO RESULT (ROLL, SCODE, MARKS) VALUES (13, 5, 80);
INSERT INTO RESULT (ROLL, SCODE, MARKS) VALUES (14, 5, 20);
UPDATE RESULT SET MARKS = 90 WHERE (ROLL, SCODE) = (12, 5);
SELECT * FROM RESULT;
SELECT * FROM BACKPAPER;