 SELECT * FROM EMP WHERE EMP.JN_DT>'2017-11-11';
 SELECT * FROM EMP WHERE MONTH(EMP.JN_DT)='2';
 SELECT MIN(BASIC) as 'min basic', MAX(BASIC) as 'max_basic' FROM EMP; 
 SELECT * FROM EMP WHERE SEX='F';