USE ass1;
SELECT MIN(EMP.BASIC) AS 'MIN',MAX(EMP.BASIC) AS 'MAX', AVG(EMP.BASIC) AS 'AVG',DEPARTMENT.DEPT_NAME
FROM EMP, DEPARTMENT
WHERE EMP.DEPT_CODE = DEPARTMENT.DEPT_CODE
GROUP BY DEPARTMENT.DEPT_NAME;

SELECT * 
FROM EMP, DEPARTMENT
WHERE EMP.DEPT_CODE = DEPARTMENT.DEPT_CODE AND EMP.SEX = 'F';
